---
# .aocbench.yaml version (always 1)
version: 1
# Repo Author
author: VeMeth
# Language used
language: Rust
# Path to Dockerfile to build image
dockerfile: Dockerfile
# Or image (this takes priority)
# image: rust:alpine
# Disable Hyperfine usage
# hyperfine: False
# Location where code directory should be mounted
code: /code
# [*] What directory to run code from
workdir: /code
# [*] When running image, command to run a given day.
cmd: "./target/release/day%zeroday%"
# [*] When running image, command to run once to build a given day if needed.
runonce: "cargo build --release --bin day%zeroday%"
# [*] Directories that need persisting across runs
persistence:
 - /usr/local/cargo/registry
 - /var/cache/apk
# [*] Environment vars to set on container
environment: []
# [*] Path to per-day code.
daypath: "src/day%zeroday%/main.rs"
# [*] Path to per-day input file.
inputfile: "day%zeroday%/data/input.txt"
# [*] Path to per-day answer file.
answerfile: "day%zeroday%/data/answer.txt"
